"""add_departments_and_assets

Revision ID: 0974918eb75f
Revises: bc5d0d097cc2
Create Date: 2026-07-12 12:02:26.998616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0974918eb75f'
down_revision: Union[str, None] = 'bc5d0d097cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('head', sa.String(length=255), nullable=True),
    sa.Column('parent', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=True)
    op.add_column('assests', sa.Column('asset_tag', sa.String(length=50), nullable=False))
    op.add_column('assests', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('assests', sa.Column('serial_number', sa.String(length=255), nullable=False))
    op.add_column('assests', sa.Column('location', sa.String(length=255), nullable=False))
    op.add_column('assests', sa.Column('status', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_assests_asset_tag'), 'assests', ['asset_tag'], unique=True)
    op.create_index(op.f('ix_assests_category'), 'assests', ['category'], unique=False)
    op.create_index(op.f('ix_assests_serial_number'), 'assests', ['serial_number'], unique=True)
    op.drop_column('assests', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assests', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_assests_serial_number'), table_name='assests')
    op.drop_index(op.f('ix_assests_category'), table_name='assests')
    op.drop_index(op.f('ix_assests_asset_tag'), table_name='assests')
    op.drop_column('assests', 'status')
    op.drop_column('assests', 'location')
    op.drop_column('assests', 'serial_number')
    op.drop_column('assests', 'category')
    op.drop_column('assests', 'asset_tag')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
