"""add_allocation_and_history

Revision ID: 158a0dac8797
Revises: 7102d9c0677c
Create Date: 2026-07-12 14:12:15.562184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '158a0dac8797'
down_revision: Union[str, None] = '7102d9c0677c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(length=50), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('emp_id', sa.String(length=100), nullable=False),
    sa.Column('person', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('assigned_date', sa.DateTime(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_name', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocations_asset_tag'), 'allocations', ['asset_tag'], unique=False)
    op.create_index(op.f('ix_allocations_id'), 'allocations', ['id'], unique=False)
    op.create_table('allocation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=True),
    sa.Column('asset_tag', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=500), nullable=False),
    sa.Column('performed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('performed_by_name', sa.String(length=255), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocation_history_asset_tag'), 'allocation_history', ['asset_tag'], unique=False)
    op.create_index(op.f('ix_allocation_history_id'), 'allocation_history', ['id'], unique=False)
    op.add_column('assests', sa.Column('tag', sa.String(length=50), nullable=False))
    op.add_column('assests', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('assests', sa.Column('current_holder', sa.String(length=255), nullable=True))
    op.add_column('assests', sa.Column('condition', sa.String(length=50), nullable=False))
    op.alter_column('assests', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_assests_asset_tag'), table_name='assests')
    op.drop_index(op.f('ix_assests_category'), table_name='assests')
    op.drop_index(op.f('ix_assests_serial_number'), table_name='assests')
    op.create_index(op.f('ix_assests_tag'), 'assests', ['tag'], unique=True)
    op.drop_column('assests', 'asset_tag')
    op.drop_column('assests', 'serial_number')
    op.drop_column('assests', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assests', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('assests', sa.Column('serial_number', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('assests', sa.Column('asset_tag', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_assests_tag'), table_name='assests')
    op.create_index(op.f('ix_assests_serial_number'), 'assests', ['serial_number'], unique=True)
    op.create_index(op.f('ix_assests_category'), 'assests', ['category'], unique=False)
    op.create_index(op.f('ix_assests_asset_tag'), 'assests', ['asset_tag'], unique=True)
    op.alter_column('assests', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('assests', 'condition')
    op.drop_column('assests', 'current_holder')
    op.drop_column('assests', 'description')
    op.drop_column('assests', 'tag')
    op.drop_index(op.f('ix_allocation_history_id'), table_name='allocation_history')
    op.drop_index(op.f('ix_allocation_history_asset_tag'), table_name='allocation_history')
    op.drop_table('allocation_history')
    op.drop_index(op.f('ix_allocations_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_asset_tag'), table_name='allocations')
    op.drop_table('allocations')
    # ### end Alembic commands ###
