"""add_maintenance_and_audit

Revision ID: 7102d9c0677c
Revises: e3433a8f7335
Create Date: 2026-07-12 13:46:59.612393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7102d9c0677c'
down_revision: Union[str, None] = 'e3433a8f7335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
