"""add_asset_manager_fields

Revision ID: 9177a4780716
Revises: 3f00637a9cd4
Create Date: 2026-07-12 16:11:40.191704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9177a4780716'
down_revision: Union[str, None] = '3f00637a9cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_email'), 'password_reset_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.add_column('assests', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('assests', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('assests', sa.Column('brand', sa.String(length=255), nullable=True))
    op.add_column('assests', sa.Column('model', sa.String(length=255), nullable=True))
    op.add_column('assests', sa.Column('serial_number', sa.String(length=255), nullable=True))
    op.add_column('assests', sa.Column('manufacturer', sa.String(length=255), nullable=True))
    op.add_column('assests', sa.Column('purchase_date', sa.String(length=50), nullable=True))
    op.add_column('assests', sa.Column('warranty_expiry', sa.String(length=50), nullable=True))
    op.add_column('assests', sa.Column('cost', sa.String(length=50), nullable=True))
    op.add_column('assests', sa.Column('supplier', sa.String(length=255), nullable=True))
    op.add_column('assests', sa.Column('is_shared', sa.Boolean(), nullable=False))
    op.add_column('assests', sa.Column('is_bookable', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assests', 'is_bookable')
    op.drop_column('assests', 'is_shared')
    op.drop_column('assests', 'supplier')
    op.drop_column('assests', 'cost')
    op.drop_column('assests', 'warranty_expiry')
    op.drop_column('assests', 'purchase_date')
    op.drop_column('assests', 'manufacturer')
    op.drop_column('assests', 'serial_number')
    op.drop_column('assests', 'model')
    op.drop_column('assests', 'brand')
    op.drop_column('assests', 'department')
    op.drop_column('assests', 'category')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_email'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
