"""add_categories_locations_roles

Revision ID: 9f8b8fbac993
Revises: 7c24f6a6e843
Create Date: 2026-07-12 12:16:31.242301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8b8fbac993'
down_revision: Union[str, None] = '7c24f6a6e843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
